# fly.toml app configuration file generated for choicemaster on 2023-07-29T17:16:42+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "choicemaster"
primary_region = "hkg"

[build]
image = "ghcr.io/hotjuicew/choicemaster-telegram-bot:latest"


